version: '3.4'

services:
  saabackend:
    image: nitinsaa1999/saabackend:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000